// <auto-generated />
using System;
using Kaloom.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kaloom.API.Migrations
{
    [DbContext(typeof(KaloomContext))]
    [Migration("20251112232710_SeedStudentType")]
    partial class SeedStudentType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kaloom.API.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.Property<int>("IdTipoAluno")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(24)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("varchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoAluno");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Kaloom.API.Models.Etec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeUnidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Etecs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeUnidade = "Etec JK - Sede"
                        },
                        new
                        {
                            Id = 2,
                            NomeUnidade = "Etec JK - Extensão Céu Caminho do Mar"
                        },
                        new
                        {
                            Id = 3,
                            NomeUnidade = "Etec JK - Extensão Associação Comunitária Despertar"
                        },
                        new
                        {
                            Id = 4,
                            NomeUnidade = "Etec Lauro Gomes"
                        },
                        new
                        {
                            Id = 5,
                            NomeUnidade = "Etec Jorge Street"
                        });
                });

            modelBuilder.Entity("Kaloom.API.Models.Fatec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeUnidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Fatecs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeUnidade = "Fatec Diadema - \"Luigi Papaiz\""
                        },
                        new
                        {
                            Id = 2,
                            NomeUnidade = "Fatec SBC - \"Adib Moisés Dib\""
                        },
                        new
                        {
                            Id = 3,
                            NomeUnidade = "Fatec São Paulo"
                        });
                });

            modelBuilder.Entity("Kaloom.API.Models.TipoAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Etec")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Fatec")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("StatusEtec")
                        .HasColumnType("int");

                    b.Property<int?>("StatusFatec")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fatec", "Etec", "StatusFatec", "StatusEtec")
                        .IsUnique();

                    b.ToTable("TipoAlunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Etec = false,
                            Fatec = true,
                            StatusFatec = 1
                        },
                        new
                        {
                            Id = 2,
                            Etec = false,
                            Fatec = true,
                            StatusFatec = 2
                        },
                        new
                        {
                            Id = 3,
                            Etec = true,
                            Fatec = false,
                            StatusEtec = 1
                        },
                        new
                        {
                            Id = 4,
                            Etec = true,
                            Fatec = false,
                            StatusEtec = 2
                        },
                        new
                        {
                            Id = 5,
                            Etec = true,
                            Fatec = true,
                            StatusEtec = 1,
                            StatusFatec = 1
                        },
                        new
                        {
                            Id = 6,
                            Etec = true,
                            Fatec = true,
                            StatusEtec = 2,
                            StatusFatec = 1
                        },
                        new
                        {
                            Id = 7,
                            Etec = true,
                            Fatec = true,
                            StatusEtec = 1,
                            StatusFatec = 2
                        },
                        new
                        {
                            Id = 8,
                            Etec = true,
                            Fatec = true,
                            StatusEtec = 2,
                            StatusFatec = 2
                        });
                });

            modelBuilder.Entity("Kaloom.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Kaloom.API.Models.Aluno", b =>
                {
                    b.HasOne("Kaloom.API.Models.TipoAluno", "TipoAluno")
                        .WithMany("Alunos")
                        .HasForeignKey("IdTipoAluno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kaloom.API.Models.Usuario", "Usuario")
                        .WithOne("Aluno")
                        .HasForeignKey("Kaloom.API.Models.Aluno", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoAluno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Kaloom.API.Models.TipoAluno", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("Kaloom.API.Models.Usuario", b =>
                {
                    b.Navigation("Aluno")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
