// <auto-generated />
using System;
using Kaloom.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kaloom.Infrastructure.Migrations
{
    [DbContext(typeof(KaloomContext))]
    [Migration("20251029202340_UpdateStudentMigrations")]
    partial class UpdateStudentMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kaloom.API.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdTipoAluno")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoAluno");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Kaloom.API.Models.Etec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeUnidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Etecs", (string)null);
                });

            modelBuilder.Entity("Kaloom.API.Models.Fatec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeUnidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Fatecs", (string)null);
                });

            modelBuilder.Entity("Kaloom.API.Models.TipoAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Etec")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Fatec")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("StatusEtec")
                        .HasColumnType("int");

                    b.Property<int?>("StatusFatec")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TipoAlunos");
                });

            modelBuilder.Entity("Kaloom.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Kaloom.API.Models.Aluno", b =>
                {
                    b.HasOne("Kaloom.API.Models.TipoAluno", "TipoAluno")
                        .WithMany()
                        .HasForeignKey("IdTipoAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kaloom.API.Models.Usuario", "Usuario")
                        .WithOne("Aluno")
                        .HasForeignKey("Kaloom.API.Models.Aluno", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoAluno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Kaloom.API.Models.Usuario", b =>
                {
                    b.Navigation("Aluno")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
